# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squrl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squrls',
            fields=[
                ('squrl', models.SlugField(max_length=7, primary_key=True, serialize=False)),
                ('long_url', models.URLField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('access_date', models.DateTimeField(auto_now=True)),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
