# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squrl', '0002_auto_20170813_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squrls',
            old_name='long_url',
            new_name='target',
        ),
    ]
