# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squrl', '0003_auto_20170813_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squrls',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
